// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
use proofman_common::GenericTrace;
use proofman_common::PackedInfoConst;
pub use proofman_macros::trace_row;
pub use proofman_macros::values;
use fields::PrimeField64;
use std::fmt;

#[allow(dead_code)]
type FieldExtension<F> = [F; 3];

pub const PILOUT_HASH: &str = "f890a6bfa9dba3e382198291befdcae6757c2d0624f9b736d166da14903ca7f8";

pub const MERKLE_TREE_ARITY: u64 = 4;

//AIRGROUP CONSTANTS

pub const HASHES_AIRGROUP_ID: usize = 0;

//AIR CONSTANTS

pub const SHA_2_AIR_IDS: &[usize] = &[0];

pub const BLAKE_2_B_AIR_IDS: &[usize] = &[1];

pub const BLAKE_3_AIR_IDS: &[usize] = &[2];

  
trace_row!(Sha2FixedRow<F> {
 CLK_0: F, RANGE1: F, RANGE2: F, RANGE3: F, __L1__: F,
});
pub type Sha2Fixed<F> = GenericTrace<Sha2FixedRow<F>, 65536, 0, 0>;

trace_row!(Sha2TraceRow<F> {
 s0:[bit; 32], s1:[bit; 32], w:[bit; 32], new_s0_carry_bits:ubit(3), new_s1_carry_bits:ubit(3), new_w_carry_bits:ubit(2), mul_range:u64,
});

pub type Sha2Trace<R> = GenericTrace<R, 65536, 0, 0>;

trace_row!(Blake2bFixedRow<F> {
 CLK_0: F, BLOCK_ID: F, RANGE: F, A: F, B: F, C: F, __L1__: F,
});
pub type Blake2bFixed<F> = GenericTrace<Blake2bFixedRow<F>, 65536, 0, 1>;

trace_row!(Blake2bTraceRow<F> {
 va:[u16; 4], vb:[u8; 8], vc:[u16; 4], vd:[u8; 8], x:[u16; 4], y:[u16; 4], va_prime:[u8; 8], vd_prime:[u8; 8], vc_prime:[u8; 8], vb_prime:[u8; 8], va_prime_prime:[u8; 8], vd_prime_prime:[u8; 8], vc_prime_prime:[u8; 8], vb_pp_xor:[u8; 8], vb_pp_t:[bit; 2], mul_range:u64, mul_table:u64,
});

pub type Blake2bTrace<R> = GenericTrace<R, 65536, 0, 1>;

trace_row!(Blake3FixedRow<F> {
 CLK_0: F, BLOCK_ID: F, RANGE: F, A: F, B: F, OFFSET: F, ROTATION: F, C_ROT: [F; 2], __L1__: F,
});
pub type Blake3Fixed<F> = GenericTrace<Blake3FixedRow<F>, 1048576, 0, 2>;

trace_row!(Blake3TraceRow<F> {
 va:[u16; 2], vb:[u8; 4], vc:[u16; 2], vd:[u8; 4], x:[u16; 2], y:[u16; 2], va_prime:[u8; 4], vd_prime:[u8; 4], vc_prime:[u8; 4], vb_prime_s:[[u8; 2]; 4], va_prime_prime:[u8; 4], vd_prime_prime:[u8; 4], vc_prime_prime:[u8; 4], vb_prime_prime_s:[u32; 4], mul_range:u64, mul_table:u64,
});

pub type Blake3Trace<R> = GenericTrace<R, 1048576, 0, 2>;

values!(Sha2AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(Blake2bAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(Blake3AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

pub const PACKED_INFO: &[(usize, usize, PackedInfoConst)] = &[
    (0, 0, PackedInfoConst {
        is_packed: true,
        num_packed_words: 3,
        unpack_info: &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 2, 64],
    }),
    (0, 1, PackedInfoConst {
        is_packed: true,
        num_packed_words: 17,
        unpack_info: &[16, 16, 16, 16, 8, 8, 8, 8, 8, 8, 8, 8, 16, 16, 16, 16, 8, 8, 8, 8, 8, 8, 8, 8, 16, 16, 16, 16, 16, 16, 16, 16, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 64, 64],
    }),
    (0, 2, PackedInfoConst {
        is_packed: true,
        num_packed_words: 11,
        unpack_info: &[16, 16, 8, 8, 8, 8, 16, 16, 8, 8, 8, 8, 16, 16, 16, 16, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 32, 32, 32, 32, 64, 64],
    }),
];

/// Display name for every `(airgroup_id, air_id)` pair, derived directly from the
/// PILOUT. Lets code resolve an AIR name without a loaded setup/`GlobalInfo`.
pub const AIR_NAMES: &[(usize, usize, &str)] = &[
    (0, 0, "Sha2"),
    (0, 1, "Blake2b"),
    (0, 2, "Blake3"),
];